version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-neighbors
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: neighbors
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
  redis:
    image: redis:8.0-M03-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

volumes:
  postgres_data:
  cache:
    driver: local

networks:
  backend-network:
    driver: bridge
