spring:
  application:
    name: neighbors-api
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    redis:
      host: localhost
      port: 6379
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  cache:
    type: redis

server:
  port: 8082
springdoc:
  api-docs.enabled: true
  swagger-ui.path: /swagger-ui.html